import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { tw } from 'twind'
import { getPackageVersion } from '../../../../lib/database'
import Breadcrumbs from '../../../../components/Breadcrumbs'
import { formatAddressOrEnsName } from '../../../../lib/ens'

const Package: NextPage = ({ pkgVersion }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pkgVersion.cid ? (
        <>
          <Breadcrumbs
            author={pkgVersion.package.author}
            name={pkgVersion.package.name}
            cid={pkgVersion.cid}
          />
        </>
      ) : (
        <>Package version not found</>
      )}
    </div>
  )
}

export async function getServerSideProps({ query }) {
  const { author, name, cid } = query
  const formattedAuthor = await formatAddressOrEnsName(author)
  if (formattedAuthor.ensName && formattedAuthor.ensName !== author) {
    return {
      redirect: {
        destination: `/pkg/${ensName}/${name}/${version}`,
        permanent: false,
      },
    }
  }

  let pkgVersion = await getPackageVersion({
    authorAddress: formattedAuthor.address,
    name,
    cid,
  })

  pkgVersion.package.author = formattedAuthor

  return {
    props: { pkgVersion },
  }
}

export default Package
